import type { L } from "./i18n";

export const ui = {
  skipToContent: { ko: "본문 바로가기", en: "Skip to content" },
  nav: { ko: "주요", en: "Primary" },
  projects: { ko: "Projects", en: "Projects" },
  blog: { ko: "Blog", en: "Blog" },
  toc: { ko: "목차", en: "Contents" },
  tocLabel: { ko: "프로젝트 목차", en: "Project contents" },
  stack: { ko: "스택", en: "Stack" },
  links: { ko: "링크", en: "Links" },
  live: { ko: "라이브", en: "Live" },
  livePreparing: { ko: "준비 중", en: "Not public yet" },
  repo: { ko: "저장소", en: "Repo" },
  decisionsHeading: { ko: "결정과 측정", en: "Decisions and measurements" },
  notFound: { ko: "여기에는 아무것도 없다.", en: "Nothing lives here." },
  goHome: { ko: "홈으로", en: "Go home" },
  demoCaption: { ko: "데모 와이어프레임", en: "Demo wireframe" },
  photoCaption: { ko: "사진 자리표시자", en: "Photo placeholder" },
  home: { ko: "홈", en: "Home" },
  linkedin: { ko: "링크드인", en: "LinkedIn" },
  email: { ko: "이메일", en: "Email" },
  meta: { ko: "정보", en: "Details" },
  year: { ko: "연도", en: "Year" },
  published: { ko: "작성일", en: "Published" },
  breadcrumb: { ko: "위치", en: "Breadcrumb" },
  prev: { ko: "이전", en: "Previous" },
  next: { ko: "다음", en: "Next" },
  pagerLabel: { ko: "글 이동", en: "Post navigation" },
  projectPagerLabel: { ko: "프로젝트 이동", en: "Project navigation" },
  switchCode: { ko: "EN", en: "KO" },
  switchLabel: { ko: "Switch to English", en: "한국어로 전환" },
} satisfies Record<string, L>;
